name: nirwanagrid
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  http: ^1.5.0
  lottie: ^3.3.2
  chat_bubbles: ^1.7.0
  google_generative_ai: ^0.4.3
  mqtt_client: ^10.11.1
  flutter_dotenv: ^6.0.0
  amplify_flutter: ^2.6.5
  amplify_storage_s3: ^2.6.5
  amplify_auth_cognito: ^2.6.5
  syncfusion_flutter_gauges: ^31.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/guest.png
    - assets/images/home.png
    - assets/images/explore.png
    - assets/images/security.png
    - assets/images/settings.png
    - assets/images/back.png
    - assets/api_key.txt
    - assets/robot.json
    - assets/FAQ.json

